import { createContext, useContext, useState, type ReactNode } from "react"

// ── Locale types ──────────────────────────────────────────────────────────────
export const UI_LOCALES = ["es", "en"] as const
export type UiLocale = (typeof UI_LOCALES)[number]

export const AI_LANG_CODES = [
  "auto",
  "es",
  "en",
  "fr",
  "pt",
  "de",
  "it",
  "ja",
  "zh",
  "ar",
  "ru",
] as const
export type AiLang = (typeof AI_LANG_CODES)[number]

/** Full language name in Spanish — used to override the AI system prompt */
export const AI_LANG_NAMES: Record<Exclude<AiLang, "auto">, string> = {
  es: "español",
  en: "inglés",
  fr: "francés",
  pt: "portugués",
  de: "alemán",
  it: "italiano",
  ja: "japonés",
  zh: "chino",
  ar: "árabe",
  ru: "ruso",
}

// ── Translations ──────────────────────────────────────────────────────────────
const translations = {
  es: {
    landing: {
      subtitle: "La enciclopedia libre generada por inteligencia artificial",
      modes: {
        rapido: { label: "Rápido", desc: "Breve y directo" },
        medio: { label: "Medio", desc: "Con buen detalle" },
        extendido: { label: "Extendido", desc: "Estilo Wikipedia completo" },
      },
      searchPlaceholder: "Buscar cualquier tema...",
      searchButton: "Buscar",
      recents: "Recientes",
      suggestions: "Sugerencias",
      suggestionItems: [
        "Inteligencia Artificial",
        "Agujeros Negros",
        "Historia de Roma",
        "Computación Cuántica",
        "Fotosíntesis",
        "Relatividad General",
      ],
      removeRecent: (q: string) => `Eliminar ${q} de recientes`,
    },
    header: {
      searchPlaceholder: "Buscar en WikipedIA…",
      openMenu: "Abrir menú",
      backToHome: "Volver al inicio",
      toggleTheme: "Cambiar tema",
      settings: "Configuración",
    },
    article: {
      aiThinking: "Pensamiento de la IA",
      generating: "Generando...",
      words: "palabras",
      readingTime: "min de lectura",
      errorTitle: "Error al generar el artículo",
      errorRetry: "Intentar de nuevo",
      copy: "Copiar",
      copied: "Copiado",
      share: "Compartir",
      shared: "¡Enlace copiado!",
      download: "Descargar",
      expandImage: "Ver imagen",
    },
    app: {
      navigation: "Navegación",
      backToTop: "Volver arriba",
    },
    toolbar: {
      copy: "Copiar",
      copied: "Copiado",
      search: "Buscar",
      removeHighlight: "Quitar",
      colors: {
        yellow: "Amarillo",
        green: "Verde",
        blue: "Azul",
        pink: "Rosa",
        orange: "Naranja",
      },
    },
    footer: {
      disclaimerPre: "El contenido de",
      disclaimerPost:
        "es generado por IA y puede contener inexactitudes. Verifica siempre con fuentes confiables.",
      hosting: "Hosting por",
    },
    settings: {
      uiLanguage: "Idioma de la interfaz",
      aiLanguage: "Idioma de respuesta de la IA",
      aiLangs: {
        auto: "Automático",
        es: "Español",
        en: "Inglés",
        fr: "Francés",
        pt: "Portugués",
        de: "Alemán",
        it: "Italiano",
        ja: "Japonés",
        zh: "Chino",
        ar: "Árabe",
        ru: "Ruso",
      },
    },
  },
  en: {
    landing: {
      subtitle: "The free encyclopedia generated by artificial intelligence",
      modes: {
        rapido: { label: "Quick", desc: "Brief and direct" },
        medio: { label: "Medium", desc: "Good amount of detail" },
        extendido: { label: "Extended", desc: "Full Wikipedia style" },
      },
      searchPlaceholder: "Search any topic...",
      searchButton: "Search",
      recents: "Recent",
      suggestions: "Suggestions",
      suggestionItems: [
        "Artificial Intelligence",
        "Black Holes",
        "History of Rome",
        "Quantum Computing",
        "Photosynthesis",
        "General Relativity",
      ],
      removeRecent: (q: string) => `Remove ${q} from recent`,
    },
    header: {
      searchPlaceholder: "Search WikipedIA…",
      openMenu: "Open menu",
      backToHome: "Back to home",
      toggleTheme: "Toggle theme",
      settings: "Settings",
    },
    article: {
      aiThinking: "AI Thinking",
      generating: "Generating...",
      words: "words",
      readingTime: "min read",
      errorTitle: "Error generating the article",
      errorRetry: "Try again",
      copy: "Copy",
      copied: "Copied",
      share: "Share",
      shared: "Link copied!",
      download: "Download",
      expandImage: "View image",
    },
    app: {
      navigation: "Navigation",
      backToTop: "Back to top",
    },
    toolbar: {
      copy: "Copy",
      copied: "Copied",
      search: "Search",
      removeHighlight: "Remove",
      colors: {
        yellow: "Yellow",
        green: "Green",
        blue: "Blue",
        pink: "Pink",
        orange: "Orange",
      },
    },
    footer: {
      disclaimerPre: "The content of",
      disclaimerPost:
        "is AI-generated and may contain inaccuracies. Always verify with reliable sources.",
      hosting: "Hosted by",
    },
    settings: {
      uiLanguage: "Interface language",
      aiLanguage: "AI response language",
      aiLangs: {
        auto: "Automatic",
        es: "Spanish",
        en: "English",
        fr: "French",
        pt: "Portuguese",
        de: "German",
        it: "Italian",
        ja: "Japanese",
        zh: "Chinese",
        ar: "Arabic",
        ru: "Russian",
      },
    },
  },
} as const

type Translations = typeof translations

// ── Context ───────────────────────────────────────────────────────────────────
interface I18nContextValue {
  uiLocale: UiLocale
  setUiLocale: (l: UiLocale) => void
  aiLang: AiLang
  setAiLang: (l: AiLang) => void
  t: Translations[UiLocale]
}

const I18nCtx = createContext<I18nContextValue | null>(null)

export function I18nProvider({ children }: { children: ReactNode }) {
  const [uiLocale, setUiLocaleState] = useState<UiLocale>(() => {
    const stored = localStorage.getItem("wikia-ui-lang")
    return (UI_LOCALES as readonly string[]).includes(stored ?? "")
      ? (stored as UiLocale)
      : "es"
  })

  const [aiLang, setAiLangState] = useState<AiLang>(() => {
    const stored = localStorage.getItem("wikia-ai-lang")
    return (AI_LANG_CODES as readonly string[]).includes(stored ?? "")
      ? (stored as AiLang)
      : "auto"
  })

  function setUiLocale(l: UiLocale) {
    localStorage.setItem("wikia-ui-lang", l)
    setUiLocaleState(l)
  }

  function setAiLang(l: AiLang) {
    localStorage.setItem("wikia-ai-lang", l)
    setAiLangState(l)
  }

  return (
    <I18nCtx.Provider
      value={{
        uiLocale,
        setUiLocale,
        aiLang,
        setAiLang,
        t: translations[uiLocale],
      }}
    >
      {children}
    </I18nCtx.Provider>
  )
}

export function useI18n(): I18nContextValue {
  const ctx = useContext(I18nCtx)
  if (!ctx) throw new Error("useI18n must be used inside <I18nProvider>")
  return ctx
}
